server:
  port: 8084

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.platform.notificationservice.event.PaymentEvent

kafka:
  topics:
    payment-success: payment.success
    payment-failed: payment.failed
    inventory-failed: inventory.failed

logging:
  level:
    com.platform: DEBUG