apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  ORDER_SERVICE_URL: "http://order-service:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service:8082"
  PAYMENT_SERVICE_URL: "http://payment-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"